apiVersion: v1
kind: Service
metadata:
  name: puzzle-service
  labels:
    app: puzzle-service
    tier: backend
    env: dev
spec:
  ports:
    - port: 32000
      targetPort: puzzle-service
  selector:
    app: puzzle-service
    tier: backend
    env: dev
