apiVersion: v1
kind: Service
metadata:
  name: puzzle-service
  labels:
    app: puzzle-service
    tier: backend
    env: dev
spec:
  type: NodePort
  ports:
    - port: 5000
      nodePort: 32000
  selector:
    app: puzzle-service
    tier: backend
    env: dev
