version: '2'

services:
  puzzles:
    image: klmcwhirter/puzzles:x86_64
    build:
      context: ./PublishOutput/
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_CLI_TELEMETRY_OPTOUT=1
